version: '3'
services:
    app:
        container_name: spring-devboard
        image: v6yang/devboard
        ports:
            - '5000:5000'
    mongo:
        container_name: mongo
        image: mongo:4.4.2
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: dbUserPassword123
        volumes:
            - ./data:/data/db
